### ISSUE TITLE
BUG: Memory Leak

### ISSUE THREAD

**Issue by walljm** [crispthinking/IronRe2#7]
Using a simple program to test...

```
 private static void Main(string[] args)
        {
            var str = "qwer123w8e4r5t6";
            var regex = @"\w+\d+\w\d\w\d";

            for (var i = 1; i < 100000; i++)
            {
                using (var exp = new IronRe2.Regex(regex))
                {
                    Console.WriteLine(exp.IsMatch(str));
                }
            }

            while (true)
            {
                Thread.Sleep(1000);
            }
        }
```

produces about 400mb of memory that never gets reclaimed

**Comment by iwillspeak** [comment]
Thanks for the report. I’ve verified the behaviour on64 bit Linux at least. It seems that just the regex allocation and delete pair is all that is required. Looking at gcdump output it doesn’t look like we are leaking managed resources.

**Comment by iwillspeak** [comment]
The leak appears to be down to not calling the `cre2_delete` properly in the `UnmanagedResource` class.
